export const ActionTypes = {
    FETCH_PRODUCTS_START:'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_FAILED:'FETCH_PRODUCTS_FAILED',
    SET_PRODUCTS: 'SET_PRODUCTS',
    ORDER_PRODUCTS_BY_PRICE: 'ORDER_PRODUCTS_BY_PRICE',
    FILTER_PRODUCTS_BY_CATEGORY: 'FILTER_PRODUCTS_BY_CATEGORY',
    ADD_TO_CART : 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    INCREMENT_INTO_CART:'INCREMENT_INTO_CART',
    DECREMENT_FROM_CART:'DECREMENT_FROM_CART',
}