export const ActionTypes = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    SET_PRODUCTS: 'SET_PRODUCTS',
    ORDER_PRODUCTS_BY_PRICE: 'ORDER_PRODUCTS_BY_PRICE',
    FILTER_PRODUCTS_BY_CATEGORY: 'FILTER_PRODUCTS_BY_CATEGORY'
}